### ISSUE TITLE
How should InstanaSpanBuilder::asChildOf treat null parent?

### ISSUE THREAD

**Issue by elgris** [instana/instana-java-opentracing#2]
Hi!
I have a question about behaviour of [InstanaSpanBuilder::asChildOf method](https://github.com/instana/instana-java-opentracing/blob/master/src/main/java/com/instana/opentracing/InstanaSpanBuilder.java#L36) . 

```java
    public Tracer.SpanBuilder asChildOf(BaseSpan<?> parent) {
        return asChildOf(parent.context());
    }
```
Should it treat null parent as noop? At least, official Opentracing definition if `Tracer` interface [suggests that](https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/Tracer.java#L106).

**Comment by CodingFabian** [comment]
You are right. this clarification was added in 0.30 of opentracing. We clearly do not reflect that (worse, it would null pointer at the moment)

**Comment by CodingFabian** [comment]
pushed as 0.30.1 into sonatype, syncing to central now.

Thanks for your report!
