### ISSUE TITLE
Make extraction of span context consistent with other implementations

### ISSUE THREAD

**Issue by elgris** [instana/instana-java-opentracing#3]
Instana Tracer extracts all headers from HTTP request into context (including sensitive headers like `Authorization`, `Host`, etc). However, other implementations (like python implementation) extract only those headers which belong to Instana (i.e. `X-Instana-S`, `X-Instana-T`, etc).

As a user I'd expect consistent behaviour among different implementations. And AFAIK Instana does not officially support Opentracing baggage items for now. Does it make sense to modify `InstanaTracer` to operate only  `X-Instana-*` headers in `extract` and `inject` method? In this case baggage support will be dropped (which is consistent with other implementations).

**Comment by CodingFabian** [comment]
Hi @elgris,
yes we are going to change that behaviour to what you are suggesting. We will keep you updated

**Comment by taylora433** [comment]
Any news on this?

We don't want to be sending any extra headers downstream that are not needed if only X-Instana-* headers are needed.

**Comment by mrajaian** [comment]
Fixed in version 0.33.2, thank you!
